=== vraned/FMB/Firmware/WindowsFLDTestApp/Test Fluidics/CytovilleFluidics.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
David Vrane v1.0 07/21/2015-->
<xs:schema id="CytovilleFluidics" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CytovilleFluidics">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Mode" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ModeName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z,&quot;_&quot;]+" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Description" type="xs:string"></xs:element>
              <xs:element name="TimeSegment" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Description" type="xs:string"></xs:element>
                    <xs:element name="Time">
                      <xs:simpleType>
                        <xs:union>
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:pattern value="KT[0-9][0-9]" />
                            </xs:restriction>
                          </xs:simpleType>
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="SITU" />
                              <xs:enumeration value="SITP"></xs:enumeration>
                              <xs:enumeration value="SITD" />
                              <xs:enumeration value="TUBE" />
                              <xs:enumeration value="NO_TUBE" />
                              <xs:enumeration value="TOGG" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:union>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Valve">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="V1" type="OnOff"></xs:element>
                          <xs:element name="V2" type="OnOff"></xs:element>
                          <xs:element name="V3" type="OnOff"></xs:element>
                          <xs:element name="V4" type="OnOff"></xs:element>
                          <xs:element name="V5" type="OnOff"></xs:element>
                          <xs:element name="V6" type="OnOff"></xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Pump">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="VACUUM">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Diff" />
                                <xs:enumeration value="Off" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="P1" type="OnOff"></xs:element>
                          <xs:element name="P2" type="OnOff"></xs:element>
                          <xs:element name="P3" type="OnOff"></xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Sample">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="FlowRate">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Hold" />
                                <xs:enumeration value="High" />
                                <xs:enumeration value="Med" />
                                <xs:enumeration value="Low" />
                                <xs:enumeration value="Dyn" />
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="CalibrationTable">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Pressure">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Diff" type="xs:float"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="SampleFlow">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="High" type="xs:float"></xs:element>
                    <xs:element name="Med" type="xs:float"></xs:element>
                    <xs:element name="Low" type="xs:float"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="SIT">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="SITU" type="xs:float"></xs:element>
                    <xs:element name="SITD" type="xs:float"></xs:element>
                    <xs:element name="SITP" type="xs:float"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="TimingTable">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="KT01" type="xs:float"></xs:element>
              <xs:element name="KT02" type="xs:float"></xs:element>
              <xs:element name="KT03" type="xs:float"></xs:element>
              <xs:element name="KT04" type="xs:float"></xs:element>
              <xs:element name="KT05" type="xs:float"></xs:element>
              <xs:element name="KT06" type="xs:float"></xs:element>
              <xs:element name="KT07" type="xs:float"></xs:element>
              <xs:element name="KT08" type="xs:float"></xs:element>
              <xs:element name="KT09" type="xs:float"></xs:element>
              <xs:element name="KT10" type="xs:float"></xs:element>
              <xs:element name="KT11" type="xs:float"></xs:element>
              <xs:element name="KT12" type="xs:float"></xs:element>
              <xs:element name="KT13" type="xs:float"></xs:element>
              <xs:element name="KT14" type="xs:float"></xs:element>
              <xs:element name="KT15" type="xs:float"></xs:element>
              <xs:element name="KT16" type="xs:float"></xs:element>
              <xs:element name="KT17" type="xs:float"></xs:element>
              <xs:element name="KT18" type="xs:float"></xs:element>
              <xs:element name="KT19" type="xs:float"></xs:element>
              <xs:element name="KT20" type="xs:float"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="OnOff">
    <xs:restriction base="xs:string">
      <xs:enumeration value="On" />
      <xs:enumeration value="Off" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== vraned/FMB/Firmware/WindowsFLDTestApp/Test Fluidics/CytovilleModeTable.xml
<?xml version="1.0" encoding="utf-8"?>
<!--David Vrane 04/01/2016-->
<CytovilleFluidics xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CytovilleFluidics.xsd">
  <Mode>
    <ModeName>BOOST_RUN_HIGH</ModeName>
    <Description>This mode boosts sample into the flow cell under full vacuum prior to starting sheath flow.</Description>
    <TimeSegment>
      <Description>Wait</Description>
      <Time>TUBE</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>On</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>High</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Wait</Description>
      <Time>SITD</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>On</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>High</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT07</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>On</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>High</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT07</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>On</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>High</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT01</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>On</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>High</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Vent accumulator chamber</Description>
      <Time>KT01</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>On</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>On</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>High</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Run at high flow rate</Description>
      <Time>TOGG</Time>
      <Valve>
        <V1>On</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>On</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>High</FlowRate>
      </Sample>
    </TimeSegment>
  </Mode>
  <Mode>
    <ModeName>BOOST_RUN_MED</ModeName>
    <Description>This mode boosts sample into the flow cell under full vacuum prior to starting sheath flow.</Description>
    <TimeSegment>
      <Description>Wait</Description>
      <Time>TUBE</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Med</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Wait</Description>
      <Time>SITD</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Med</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT07</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Med</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT07</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Med</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT01</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Med</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Vent accumulator chamber</Description>
      <Time>KT02</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>On</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Med</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Run at high flow rate</Description>
      <Time>TOGG</Time>
      <Valve>
        <V1>On</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Med</FlowRate>
      </Sample>
    </TimeSegment>
  </Mode>
  <Mode>
    <ModeName>BOOST_RUN_LOW</ModeName>
    <Description>This mode boosts sample into the flow cell under full vacuum prior to starting sheath flow.</Description>
    <TimeSegment>
      <Description>Wait</Description>
      <Time>TUBE</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Low</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Wait</Description>
      <Time>SITD</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Low</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT07</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Low</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT07</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Low</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Boost sample</Description>
      <Time>KT01</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Low</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Vent accumulator chamber</Description>
      <Time>KT03</Time>
      <Valve>
        <V1>Off</V1>
        <V2>Off</V2>
        <V3>Off</V3>
        <V4>Off</V4>
        <V5>On</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
      </Pump>
      <Sample>
        <FlowRate>Low</FlowRate>
      </Sample>
    </TimeSegment>
    <TimeSegment>
      <Description>Run at high flow rate</Description>
      <Time>TOGG</Time>
      <Valve>
        <V1>On</V1>
        <V2>Off</V2>
        <V3>On</V3>
        <V4>Off</V4>
        <V5>Off</V5>
        <V6>Off</V6>
      </Valve>
      <Pump>
        <VACUUM>Diff</VACUUM>
        <P1>Off</P1>
        <P2>Off</P2>
        <P3>Off</P3>
